Apps
dannyclever/Responsive-Design- pull request #2
Opened 2019-07-31 15:15 UTC by dannyclever

This is the first Pull Request

2019-07-31 23:26 UTC, samgaco requested changes
### Hi @dannyclever and @macnick :hand: 

### Everything is looking great and the readme file looks nice :clap: , but there are some blemishes and things to adjust:

* There is a **horizontal scrolling bar** in the small screen version that shouldn't go there.

* In the **apps section until the insights section** you have the following problem for the small screen (the images are stacking to close for the first sections):
![tnw1](https://user-images.githubusercontent.com/34820784/62254728-97b61800-b3fa-11e9-86d3-2dd20f74f341.png)

* The section **Latest News** is not adapted well for the small screen:
![tnw2](https://user-images.githubusercontent.com/34820784/62254725-94229100-b3fa-11e9-916a-649358b9f394.png)


* For the large screen size, the **vertical borders** (left and right) should be a bit wider, like in the original.
![Alt Text](https://media.giphy.com/media/d6QShj0oGLRMhKGTMV/giphy.gif)

* You have to **solve the conflict** with the README.md file before the pull request.

### Work on these things and submit back for another code review :pray:

2019-07-31 23:26 UTC, samgaco commented on index.html
> +    <link rel="stylesheet" href="test.css" />
That's not the correct name of the .css file you are using for this pull request.

2019-08-01 11:35 UTC, bolah2009 commented
Currently been reviewed

2019-08-01 11:58 UTC, bolah2009 approved these changes
## Nice Job Team :clap:

The [clone](https://raw.githack.com/dannyclever/Responsive-Design-/apps/index.html) looks good to me and is responsive. :+1: 


#### Check out the comment below and [these errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Fraw.githack.com%2Fdannyclever%2FResponsive-Design-%2Fapps%2Findex.html) on using an heading (h2-h6) element in an `<article>` and `<section>` elelment, using `alt` for `<img>` elements and others. Consider checking them out before merging.

Good luck with your next project. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-08-01 11:58 UTC, bolah2009 commented on style.css
> +  /* display: block; */
Consider deleting commented out code.

2019-08-01 11:58 UTC, bolah2009 commented on style.css
> +  } */
Consider deleting commented out code

2019-08-01 14:48 UTC, merged